Bookstore tests
azzilian/onlinebookstore pull request #13
Opened 2024-05-27 23:37 UTC by azzilian

2024-05-29 03:55 UTC, azzilian commented
Gonna add some more test later on

2024-05-29 13:16 UTC, vikkushnir approved these changes
Looks very nice to me! Only, add extra lines in your SQL files

2024-05-29 13:16 UTC, vikkushnir commented on src/test/resources/database/book/remove-books-from-books-table.sql
> +DELETE FROM books WHERE Id BETWEEN 1 AND 2;
```suggestion
DELETE FROM books WHERE Id BETWEEN 1 AND 2;

```

2024-05-29 13:16 UTC, vikkushnir commented on src/test/resources/database/book/remove-books_categories-from-books_categories-table.sql
> +DELETE FROM books_categories WHERE book_id BETWEEN 1 AND 2;
```suggestion
DELETE FROM books_categories WHERE book_id BETWEEN 1 AND 2;

```

2024-05-29 13:16 UTC, vikkushnir commented on src/test/resources/database/book/remove-categories-from-categories-table.sql
> +DELETE FROM categories WHERE Id BETWEEN 1 AND 2;
```suggestion
DELETE FROM categories WHERE Id BETWEEN 1 AND 2;

```

2024-05-29 13:16 UTC, vikkushnir commented on src/test/resources/database/book/remove-lenore-from-books-table.sql
> +DELETE FROM books WHERE title = 'Lenore' and price = 10.50;
```suggestion
DELETE FROM books WHERE title = 'Lenore' and price = 10.50;

```

2024-06-03 15:05 UTC, andrii-hoienko requested changes
Nice, left some comments

2024-06-03 15:05 UTC, andrii-hoienko commented on src/test/java/com/onlinebookstore/onlinebookstore/controller/BookControllerTest.java
> +        Mockito.when(bookService.save(Mockito.any(BookRequestDto.class)))
Please use static imports

2024-06-03 15:05 UTC, andrii-hoienko commented on src/test/java/com/onlinebookstore/onlinebookstore/controller/BookControllerTest.java
> +        System.out.println("Response JSON: " + jsonResponse);
Is it necessary to write something to console?

2024-06-03 15:05 UTC, andrii-hoienko commented on src/test/java/com/onlinebookstore/onlinebookstore/controller/BookControllerTest.java
> +                .andExpect(status().isOk());
Better to check content as well

2024-06-03 15:05 UTC, andrii-hoienko commented on src/test/java/com/onlinebookstore/onlinebookstore/controller/CategoryControllerTest.java
> +    }
Code duplication, it is better to create one teardown method that clear all db and call it when required

2024-06-03 15:05 UTC, andrii-hoienko commented on src/test/java/com/onlinebookstore/onlinebookstore/controller/CategoryControllerTest.java
> +                .andExpect(jsonPath("$.description", is(categoryResponseDto.description())));
Sometimes you check content using objectMapper, sometimes via json, please choose approach and use it everywhere to be consistent

2024-06-03 15:05 UTC, andrii-hoienko commented on src/test/java/com/onlinebookstore/onlinebookstore/service/impl/CategoryServiceImplTest.java
> +        assertEquals(category.getDescription(), result.get(0).description());
check full object using only 1 assert

2024-06-03 15:05 UTC, andrii-hoienko commented on src/test/java/com/onlinebookstore/onlinebookstore/service/impl/BookServiceImplTest.java
> +        book.setTitle("Book 1");
Code duplication

2024-06-03 15:05 UTC, andrii-hoienko commented on src/test/java/com/onlinebookstore/onlinebookstore/service/impl/BookServiceImplTest.java
> +        book.setTitle("Book 1");
Actually there are a lot of duplication when you create mock objects it makes sense to make a methods for that

2024-06-03 15:05 UTC, andrii-hoienko commented on src/test/java/com/onlinebookstore/onlinebookstore/service/impl/BookServiceImplTest.java
> +    }, executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD)
Services tests should be unit, so we need to mock repository behavior. And test repo separatelly

2024-06-06 07:49 UTC, azzilian commented on src/test/java/com/onlinebookstore/onlinebookstore/controller/BookControllerTest.java
> +        System.out.println("Response JSON: " + jsonResponse);
oops, I have a lot of problems here so forgot to remove this one

2024-06-07 14:15 UTC, andrii-hoienko requested changes
Please be cerafull, and check comment once again

2024-06-07 14:15 UTC, andrii-hoienko commented on src/test/java/com/onlinebookstore/onlinebookstore/controller/BookControllerTest.java
> +                .andExpect(status().isOk());
![image](https://github.com/azzilian/onlinebookstore/assets/69054906/b40e8399-77d0-4c36-b4a4-9cad9101ecde)

2024-06-07 14:15 UTC, andrii-hoienko commented on src/test/java/com/onlinebookstore/onlinebookstore/controller/BookControllerTest.java
> +                .andExpect(status().isOk());
![image](https://github.com/azzilian/onlinebookstore/assets/69054906/a5ee6f67-d6aa-45c6-bfd1-d92e9b132215)

2024-06-07 14:15 UTC, andrii-hoienko commented on src/test/java/com/onlinebookstore/onlinebookstore/controller/BookControllerTest.java
> +                .andExpect(status().isOk());
![image](https://github.com/azzilian/onlinebookstore/assets/69054906/579946cb-4c27-44b4-b5aa-b989ed03969c)

2024-06-07 14:15 UTC, andrii-hoienko commented on src/test/java/com/onlinebookstore/onlinebookstore/service/impl/BookServiceImplTest.java
> +        Mockito.when(bookRepository.findAll(pageable)).thenReturn(bookPage);
![image](https://github.com/azzilian/onlinebookstore/assets/69054906/188eca2a-d1dc-4748-8216-b55277f925a0)

2024-06-07 14:15 UTC, andrii-hoienko commented on src/test/java/com/onlinebookstore/onlinebookstore/service/impl/BookServiceImplTest.java
> +        Mockito.when(bookMapper.toDto(book1)).thenReturn(bookResponseDto);
![image](https://github.com/azzilian/onlinebookstore/assets/69054906/aebf8e78-c83f-4557-8fa3-6f3199727701)

2024-06-27 12:23 UTC, karma-o approved these changes
Left a minor comment, other than that, it looks good :)

2024-06-27 12:23 UTC, karma-o commented on src/test/java/com/onlinebookstore/onlinebookstore/controller/CategoryControllerTest.java
> +                .andExpect(status().isOk());
please add response body assertions for this class as well

2024-06-28 09:43 UTC, merged