Bookstore dto
azzilian/onlinebookstore pull request #2
Opened 2024-04-23 19:21 UTC by azzilian

BookDto - created as a response DTO
CreateBookRequestDto - as a request DRO
pom - added dependencies & plugins & properties for mapstruck & lombok
BookController - added methods getAll(), getBookById, createBook
Updated service & repository with new method
New exception added - EntityNotFoundException
Bean removed from OnlineBookStoreApplication
application.properties - added jackson.deserialization
BookMapper added - using MapStruct to format toDto and toModel

2024-04-24 11:43 UTC, Recdt requested changes
GJ! Rejected because maybe you want to change thg from comments before review.

2024-04-24 11:43 UTC, Recdt commented on src/main/java/com/onlinebookstore/onlinebookstore/dto/CreateBookRequestDto.java
> +    private Long id;
I think this id aren't getted from request, so maybe better to delete it there

2024-04-24 11:43 UTC, Recdt commented on src/main/java/com/onlinebookstore/onlinebookstore/dto/CreateBookRequestDto.java
> +    private Long id;
![image](https://github.com/azzilian/onlinebookstore/assets/90136583/7e581ca7-926e-4553-835d-67e5eab26bb1)
in post only this parameters xd

2024-04-24 11:43 UTC, Recdt commented on src/main/java/com/onlinebookstore/onlinebookstore/exeption/EntityNotFoundException.java
> +public class EntityNotFoundException extends RuntimeException {
Maybe 1 constructor for message + exception ("", e) would be good xd

2024-04-24 11:43 UTC, Recdt commented on src/main/java/com/onlinebookstore/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +    public Optional<Book> findBookById(Long id) {
findBookById more than we need if we are in BookRepository (findById would be enough)

2024-04-24 11:43 UTC, Recdt commented on src/main/java/com/onlinebookstore/onlinebookstore/repository/impl/BookRepositoryImpl.java
>          }
Maybe catch block or why we need try(if you don't take into account that it's a try with resources)

2024-04-24 11:43 UTC, Recdt commented on src/main/java/com/onlinebookstore/onlinebookstore/service/BookService.java
> +    BookDto findBookById(Long id);
BookService findBookById

2024-04-26 09:00 UTC, azzilian commented on src/main/java/com/onlinebookstore/onlinebookstore/repository/impl/BookRepositoryImpl.java
>          }
It supoused to allow Spring to atomaticaly catch those exceptions and proceed them with @ ResponseStatus

2024-04-26 13:17 UTC, andrii-hoienko requested changes
Gj! Left minor comments

2024-04-26 13:17 UTC, andrii-hoienko commented on src/main/java/com/onlinebookstore/onlinebookstore/controller/BookController.java
> +@RequestMapping(value = "/books")
```suggestion
@RequestMapping(value = "api/books")

```

2024-04-26 13:17 UTC, andrii-hoienko commented on src/main/java/com/onlinebookstore/onlinebookstore/repository/impl/BookRepositoryImpl.java
>          }
Agree, please add catch block

2024-04-29 07:35 UTC, karma-o approved these changes
Left an important comment, please take a look at it before merging

2024-04-29 07:35 UTC, karma-o commented on src/main/java/com/onlinebookstore/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +            throw new EntityNotFoundException("Can't find book by id " + id);
we can have all sorts of exceptions caught here, and not every one of them would mean that an entity with such an id does not exist. We should throw a simple RuntimeEx or something like `DataProcessingException` like we had before

2024-04-29 11:46 UTC, merged