Bookstore global exception
azzilian/onlinebookstore pull request #4
Opened 2024-05-01 13:06 UTC by azzilian

validation for BookRequestDto added

2024-05-01 18:56 UTC, HAIOVYI approved these changes
GJ!

2024-05-01 18:56 UTC, HAIOVYI commented on src/main/java/com/onlinebookstore/onlinebookstore/dto/BookRequestDto.java
> +            + "?[0-9]+[- ]?[0-9]+[- ]?[0-9]$", message = "Invalid ISBN format, tip use ISBN-13")
I thought that  this `@Pattern` can be more simplify `@Pattern(regexp = "\\d{13}")`
what do you think ?

2024-05-02 10:22 UTC, yevheniisynytsia requested changes

2024-05-02 10:22 UTC, yevheniisynytsia commented on src/main/java/com/onlinebookstore/onlinebookstore/dto/BookRequestDto.java
> +            + "?[0-9]+[- ]?[0-9]+[- ]?[0-9]$", message = "Invalid ISBN format, tip use ISBN-13")
everything is even simpler - there is `@ISBN` annotation https://docs.jboss.org/hibernate/stable/validator/api/org/hibernate/validator/constraints/ISBN.html

2024-05-02 10:37 UTC, yevheniisynytsia approved these changes

2024-05-02 10:38 UTC, merged